title: Home
email: alex.schmitz1608@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Alexander Schmitz personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schmitzi89.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  schmitzi89

# Build settings
theme: minima
plugins:
  - jekyll-feed
  